#!/bin/bash

sudo chmod -R 755 /home/ec2-user/api
cd /home/ec2-user/api
sudo mkdir ./applogs
pip install -r requirements.txt
sudo cat > ./api/applogs/ginza.log
python3 manage.py makemigrations --settings=ginza.settings.dev
python3 manage.py migrate --settings=ginza.settings.dev